import React from "react";
import "../style/Main.css";

const Main = () => {
  return (
    <>
      <div className="main">
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
        <h1>Main</h1>
      </div>
    </>
  );
};

export default Main;
